### ISSUE TITLE
Enigmabox: wlan0 mesh-mode not working

### ISSUE THREAD

**Issue by gellenburg** [enigmagroup/enigmasuite#4]
With an attached ALFA AWUS036NEH to my Enigmabox, and WLAN Settings set to "mesh", I see a new cjdns ad-hoc network, but no other Enigmaboxes can connect.

Looking at /box/cjdroute.conf there is no…

```
"bind": "wlan0",
"beacon": 2,
```

… entry in the config.

This is affecting both the stock Enigmabox (red with white "+") as well as Enigmaboxes built with BananaPis.

**Comment by enigmagroup** [comment]
Ok, I'll investigate.

**Comment by gellenburg** [comment]
Cool. My test setup is:
1. Enigmabox (w/ VPN subscription)
   - Peered to Hyperboria through VPN
   - Peered to Hyperboria to my own node.
   - ALFA AWUS036NEH WiFi adapters
2. (5) BananaPi "enigmabox"es running firmware firmware-4G.img.gz downloaded Nov-08-2015.
3. (5) ALFA AWUS036NEH WiFi adapters

Enigmabox WLAN settings configured for mesh mode.

Each BananaPi WLAN setting configured for mesh mode.

Looking at peerStats, findnodes, or dumptable on the BananaPis shows only each local node, not any of the other nodes in the "mesh".

**_Edit:**_ FYI, Auto-Peering _is_ enabled under the Peerings link, in the Network section. On all Enigmaboxes (stock and BananaPi).

**Comment by enigmagroup** [comment]
Issue is fixed, will deploy the new image overnight.

**Comment by gellenburg** [comment]
Thanks for fixing this! Much appreciated. What's the schedule for endpoints to be updated? Mine is still on 1.7.4 and hasn't been updated to 1.7.5 yet, and I noticed that the problem is still "not fixed" in the 1.7.4 image.

**Comment by enigmagroup** [comment]
Yes, sorry, my ISP had connection issues, image is not deployed yet.
Will do this tonight if my connection is stable.

**Comment by gellenburg** [comment]
no worries. :-)

Sent from my Cyanogen phone

On Dec 5, 2015 9:44 AM, enigmagroup notifications@github.com wrote:

Yes, sorry, my ISP had connection issues, image is not deployed yet.
Will do this tonight if my connection is stable.

**Comment by enigmagroup** [comment]
...deployed!
